WITH debts AS (
SELECT 
	"company_id",
	"vendor_code",
	"customer_code",
	"biller_name_actual",
	"biller_name",
	"business_id",
	"department_code",
	"project_code",
	"entry_no",
	"document_no",
	"external_document_no",
	"transaction_no",
	"posting_group",
	"consolidation_group",
	"cust_vend_type",
	"due_date",
	"document_date",
	"payment_term_calc",
	"cust_vend_registration_no",
	"cust_vend_name",
	"last_reminder_date",
    "reminder_date",
	"description",
    "open_flag",
	"customer_search",
	"posting_date",
	"document_type_code",
	"document_type_name",
	"currency_code",
	"amount_lcy",
	"ledger_type",
	"last_payment_date",
    "customer_status_log",
    null as "source",
    "ClosedDate",
    "posting_profile"
FROM {{ref ('FO_tmp_debts') }}

UNION ALL

SELECT
	sl."company_id",
	null as "vendor_code",
	sl."customer_code",
	null as "biller_name_actual",
	null as "biller_name",
	null as "business_id",
	null as "department_code",
	null as "project_code",
	null as "entry_no",
	null as "document_no",
	null as "external_document_no",
	null as "transaction_no",
	null as "posting_group",
    'Not Group' AS consolidation_group,
    null as "cust_vend_type",
    null as "due_date",
    null as "document_date",
    null as "payment_term_calc",
    sl."cust_vend_registration_no",
    sl."cust_vend_name",
    null as "last_reminder_date",
    null AS "reminder_date",
    null as "description",
    null as "open_flag",
    null as "customer_search",
    sl."posting_date" as "posting_date",
    null as "document_type_code",
    null as "document_type_name",
    null as "currency_code",
    null as "amount_lcy",
    null as "ledger_type",
    null as "last_payment_date",
    "customer_status_log",
    'customer_status' AS "source",
    null as "ClosedDate",
    null as "posting_profile"
FROM {{ref ('FO_tmp_status_log') }}                sl
LEFT JOIN ( SELECT DISTINCT "company_id",
                "cust_vend_registration_no",
                "customer_code",
                "posting_date",
                "customer_search"
            FROM {{ref ('FO_tmp_debts') }})  d   on EQUAL_NULL(d."customer_search", CONCAT(sl."company_id",'|', sl."customer_code",'|',DATE(sl."posting_date"))) 
            WHERE d."posting_date" is null 
)

SELECT
IFNULL("company_id", ' ')	                        AS "debts.company_id",
IFNULL("vendor_code", ' ')	                        AS "debts.vendor_code",
IFNULL("customer_code", ' ')	                    AS "debts.customer_code",
IFNULL("biller_name_actual", ' ')	                AS "debts.biller_name_actual",
IFNULL("biller_name", ' ')	                        AS "debts.biller_name",
IFNULL("business_id", ' ')	                        AS "debts.business_id",
IFNULL("department_code", ' ')	                    AS "debts.department_code",
IFNULL("project_code", ' ')	                        AS "debts.project_code",
IFNULL("entry_no", 0)	                            AS "debts.entry_no",
IFNULL("document_no", ' ')	                        AS "debts.document_no",
IFNULL("external_document_no", ' ')	                AS "debts.external_document_no",
IFNULL("transaction_no", ' ')	                    AS "debts.transaction_no",
IFNULL("posting_group", ' ')	                    AS "debts.posting_group",
IFNULL("consolidation_group", ' ')	                AS "debts.consolidation_group",
IFNULL("cust_vend_type", ' ')	                    AS "debts.cust_vend_type",
CAST("due_date"   AS DATE)                          AS "debts.due_date",
CAST("document_date" AS DATE)	                    AS "debts.document_date",
IFNULL("payment_term_calc",0)	                    AS "debts.payment_term_calc",
IFNULL("cust_vend_registration_no", '')	        AS "debts.cust_vend_registration_no",
IFNULL("cust_vend_name", ' ')	                    AS "debts.cust_vend_name",
CAST("last_reminder_date" AS DATE)	                AS "debts.last_reminder_date",
CAST("reminder_date"   AS DATE)                     AS "debts.reminder_date",
IFNULL("description", ' ')	                        AS "debts.description",
"open_flag"	                                        AS "debts.open_flag",
IFNULL("customer_search", ' ')	                    AS "debts.customer_search",
CAST("posting_date"	 AS DATE)                       AS "debts.posting_date",
IFNULL("document_type_code", ' ')	                AS "debts.document_type_code",
IFNULL("document_type_name", ' ')	                AS "debts.document_type_name",
IFNULL("currency_code", ' ')	                    AS "debts.currency_code",
IFNULL("amount_lcy", 0)	                            AS "debts.amount_lcy",
IFNULL("ledger_type", ' ')	                        AS "debts.ledger_type",
CAST("last_payment_date" AS DATE)	                AS "debts.last_payment_date",
IFNULL("customer_status_log", ' ')                  AS "debts.customer_status_log",
IFNULL("source", ' ')	                            AS "debts.source",
'FO'                                                AS "debts.system",
CAST("ClosedDate"  AS DATE)                         AS "debts.CloseDate",
IFNULL("posting_profile", ' ')	                    AS "debts.posting_profile"
FROM debts