select 
"debts.company_id" 
,"debts.vendor_code" 
,"debts.customer_code" 
,"debts.biller_name_actual" 
,"debts.biller_name" 
,"debts.business_id" 
,"debts.department_code" 
,"debts.project_code" 
,"debts.entry_no" 
,"debts.document_no" 
,"debts.external_document_no" 
,"debts.transaction_no" 
,"debts.posting_group" 
,"debts.consolidation_group" 
,"debts.cust_vend_type" 
,"debts.due_date" 
,"debts.document_date" 
,"debts.payment_term_calc" 
,"debts.cust_vend_registration_no" 
,"debts.cust_vend_name" 
,"debts.last_reminder_date" 
,"debts.reminder_date" 
,"debts.description" 
,"debts.open_flag" 
,"debts.customer_search" 
,DATE('2025-05-31')                         as "debts.posting_date" 
,"debts.document_type_code" 
,"debts.document_type_name" 
,"debts.currency_code" 
,sum("debts.amount_lcy") *-1                as "debts.amount_lcy"
,"debts.ledger_type" 
,"debts.last_payment_date" 
,"debts.customer_status_log" 
,"debts.source" 
,"debts.system" 
,"debts.CloseDate"
,"debts.posting_profile"
FROM {{ ref('NAV_debts') }}
where "debts.CloseDate" = '2025-05-31'
and "debts.company_id" in ('UAB Ecoservice','AB Specializuotas transportas')

group by "debts.company_id","debts.vendor_code","debts.customer_code","debts.document_no","debts.posting_group" ,"debts.consolidation_group","debts.cust_vend_registration_no" 
,"debts.biller_name_actual" ,"debts.biller_name" ,"debts.business_id" ,"debts.due_date", "debts.document_date" ,"debts.last_reminder_date" ,"debts.reminder_date" ,"debts.last_payment_date" 
,"debts.department_code" ,"debts.project_code" ,"debts.entry_no" ,"debts.external_document_no" ,"debts.transaction_no" ,"debts.cust_vend_type" ,"debts.cust_vend_name" ,"debts.description" ,"debts.customer_search"
,"debts.document_type_code" ,"debts.document_type_name" ,"debts.currency_code" ,"debts.ledger_type" ,"debts.customer_status_log" ,"debts.source" ,"debts.system" ,"debts.CloseDate"
,"debts.payment_term_calc","debts.open_flag","debts.posting_profile"

UNION ALL 

select 
"debts.company_id" 
,"debts.vendor_code" 
,"debts.customer_code" 
,"debts.biller_name_actual" 
,"debts.biller_name" 
,"debts.business_id" 
,"debts.department_code" 
,"debts.project_code" 
,"debts.entry_no" 
,"debts.document_no" 
,"debts.external_document_no" 
,"debts.transaction_no" 
,"debts.posting_group" 
,"debts.consolidation_group" 
,"debts.cust_vend_type" 
,"debts.due_date" 
,"debts.document_date" 
,"debts.payment_term_calc" 
,"debts.cust_vend_registration_no" 
,"debts.cust_vend_name" 
,"debts.last_reminder_date" 
,"debts.reminder_date" 
,"debts.description" 
,"debts.open_flag" 
,"debts.customer_search" 
,DATE('2025-12-31')                         as "debts.posting_date" 
,"debts.document_type_code" 
,"debts.document_type_name" 
,"debts.currency_code" 
,sum("debts.amount_lcy") *-1                as "debts.amount_lcy"
,"debts.ledger_type" 
,"debts.last_payment_date" 
,"debts.customer_status_log" 
,"debts.source" 
,"debts.system" 
,"debts.CloseDate"
,"debts.posting_profile"
FROM {{ ref('NAV_debts') }}
where "debts.CloseDate" = '2025-12-31'
and "debts.company_id" in ('UAB Ecoplasta')

group by "debts.company_id","debts.vendor_code","debts.customer_code","debts.document_no","debts.posting_group" ,"debts.consolidation_group","debts.cust_vend_registration_no" 
,"debts.biller_name_actual" ,"debts.biller_name" ,"debts.business_id" ,"debts.due_date", "debts.document_date" ,"debts.last_reminder_date" ,"debts.reminder_date" ,"debts.last_payment_date" 
,"debts.department_code" ,"debts.project_code" ,"debts.entry_no" ,"debts.external_document_no" ,"debts.transaction_no" ,"debts.cust_vend_type" ,"debts.cust_vend_name" ,"debts.description" ,"debts.customer_search"
,"debts.document_type_code" ,"debts.document_type_name" ,"debts.currency_code" ,"debts.ledger_type" ,"debts.customer_status_log" ,"debts.source" ,"debts.system" ,"debts.CloseDate"
,"debts.payment_term_calc","debts.open_flag","debts.posting_profile"