WITH CTE_MY_DATE AS (
  SELECT 
    DATEADD(DAY, SEQ4(), '2005-01-01'::DATE) AS MY_DATE
  FROM TABLE(GENERATOR(ROWCOUNT => 20000)) 
)
SELECT DATE(MY_DATE) AS "date"
FROM CTE_MY_DATE 
WHERE MY_DATE <= TO_DATE(YEAR(CURRENT_DATE()) + 10 || '-12-31')
ORDER BY 1 ASC