SELECT  
    d."company_id",
	d."vendor_code",
	null as "customer_code",
	null as "biller_name_actual",
	null as "biller_name",
	d."business_id",
	d."department_code",
	d."project_code",
	d."entry_no",
	d."document_no",
	d."external_document_no",
	d."transaction_no",
	d."posting_group",
	d."consolidation_group",
	d."cust_vend_type",
	d."due_date",
	d."document_date",
	d."payment_term_calc",
	d."cust_vend_registration_no",
	d."cust_vend_name",
    null AS "reminder_date",
	d."description",
    d."open_flag",
	d."customer_search",
	d."posting_date",
	cast(d."document_type_code" as varchar) as "document_type_code",
	d."document_type_name",
	d."currency_code",
	d."amount_lcy",
    'VendorLedger'	                        AS "ledger_type",
    null	                                AS "last_payment_date",
    null                                    as "last_reminder_date",
    sl."customer_status_log"                AS "customer_status_log",
    d."ClosedDate",
    d."posting_profile"
FROM {{ref ('FO_debts_vendor') }}          d
LEFT JOIN {{ref ('FO_tmp_status_log') }}   sl on  EQUAL_NULL(d."company_id", sl."company_id") and EQUAL_NULL(d."cust_vend_registration_no",sl."cust_vend_registration_no") and EQUAL_NULL(d."posting_date", sl."posting_date")
--where d."company_id" in ('UAB Ecoservice','AB Specializuotas transportas','UAB Biržų komunalinis ūkis','UAB Ecoplasta')
UNION ALL

SELECT  
    dc."company_id",
	null as "vendor_code",
	dc."customer_code",
	dc."biller_name_actual",
	dc."biller_name",
	dc."business_id",
	dc."department_code",
	dc."project_code",
	dc."entry_no",
	dc."document_no",
	dc."external_document_no",
	dc."transaction_no",
	dc."posting_group",
	dc."consolidation_group",
	dc."cust_vend_type",
	dc."due_date",
	dc."document_date",
	dc."payment_term_calc",
	dc."cust_vend_registration_no",
	dc."cust_vend_name",
    dc."reminder_date",
	dc."description",
    dc."open_flag",
	dc."customer_search",
	dc."posting_date",
	cast(dc."document_type_code" as varchar) as "document_type_code",
	dc."document_type_name",
	dc."currency_code",
	dc."amount_lcy",
    'CustomerLedger'						AS "ledger_type",
    lpd."last_payment_date" 	            AS "last_payment_date",
    lrd."last_reminder_date" 	            AS "last_reminder_date",
    sl."customer_status_log"                AS "customer_status_log",
    dc."ClosedDate",
    dc."posting_profile"
FROM {{ref ('FO_debts_customer') }} dc
LEFT JOIN {{ref ('FO_map_last_payment_date') }}    lpd on EQUAL_NULL(concat("company_id",'|', "customer_code") , lpd."id" )
LEFT JOIN {{ref ('FO_map_last_reminder_date') }}   lrd on EQUAL_NULL(concat("company_id",'|', "customer_code") , lrd."id" )
LEFT JOIN {{ref ('FO_tmp_status_log') }}           sl  on EQUAL_NULL(dc."company_id", sl."company_id") and EQUAL_NULL(dc."cust_vend_registration_no", sl."cust_vend_registration_no")  and EQUAL_NULL(dc."posting_date",sl."posting_date")
--where dc."company_id" in ('UAB Ecoservice','AB Specializuotas transportas','UAB Biržų komunalinis ūkis','UAB Ecoplasta')